name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Sync tests tree
        run: python scripts/sync_tests.py

      - name: Lint & Format
        run: |
          ruff check .
          black --check .

      - name: Static type check
        run: mypy HackerRank LeetCode

      - name: Run tests
        run: pytest
